---

login: &login
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  encoding: unicode

development:
  database: socialmedia
  <<: *login

test:
  database: socialmedia_test
  <<: *login

production:
  database: socialmedia_production
  <<: *login